// List of 78 Indonesian State-Owned Enterprises (BUMNs)
export const COMPANIES = [
  "PT Mineral Industri Indonesia (Persero)",
  "PT Aneka Tambang Indonesia Tbk",
  "PT Bukit Asam Tbk",
  "PT Indonesia Asahan Alumunium",
  "PT Timah Tbk",
  "PT Rajawali Nusantara Indonesia (Persero)",
  "PT Perusahaan Perdagangan Indonesia",
  "PT Sang Hyang Seri",
  "PT Perikanan Indonesia",
  "PT Berdikari",
  "PT Garam",
  "PT Pupuk Indonesia (Persero)",
  "PT Petrokimia Gresik",
  "PT Pupuk Kujang",
  "PT Pupuk Kaltim",
  "PT Pupuk Iskandar Muda",
  "PT Pupuk Sriwijaya Palembang",
  "PT Rekayasa Industri",
  "PT Pupuk Indonesia Niaga",
  "PT Pupuk Indonesia Pangan",
  "PT Biro Klasifikasi Indonesia (Persero)",
  "PT Sucofindo",
  "PT Surveyor Indonesia",
  "PT LEN Industri (Persero)",
  "PT Dirgantara Indonesia",
  "PT Pindad",
  "PT PAL Indonesia",
  "PT Dahana",
  "PT Krakatau Steel (Persero) Tbk",
  "PT Pembangunan Perumahan (Persero) Tbk",
  "PT Adhi Karya (Persero) Tbk",
  "PT Wijaya Karya (Persero) Tbk",
  "PT Jasa Marga (Persero) Tbk",
  "PT Brantas Abipraya (Persero)",
  "PT Waskita Karya (Persero) Tbk",
  "PT Hutama Karya (Persero)",
  "PT Semen Indonesia (Persero) Tbk",
  "PT Semen Padang",
  "PT Semen Gresik",
  "PT Semen Tonasa",
  "PT Semen Baturaja Tbk",
  "PT Aviasi Pariwisata Indonesia (Persero)",
  "PT Angkasa Pura Indonesia",
  "PT Hotel Indonesia Natour",
  "PT Sarinah",
  "PT Taman Wisata Candi Borobudur, Prambanan dan Ratu Boko",
  "PT Pengembangan Pariwisata Indonesia",
  "PT Garuda Indonesia (Persero) Tbk",
  "PT Garuda Maintenance Facility Aero Asia Tbk",
  "PT Citilink Indonesia",
  "PT ASDP Indonesia Ferry (Persero)",
  "PT Pelayaran Nasional Indonesia (Persero)",
  "PT Pos Indonesia (Persero)",
  "PT Kereta Api Indonesia (Persero)",
  "PT Industri Kereta Api (Persero)",
  "PT Pelabuhan Indonesia (Persero)",
  "PT Pelindo Terminal Petikemas",
  "PT Pelindo Multi Terminal",
  "PT Pelindo Solusi Logistik",
  "PT Pelindo Jasa Maritim",
  "PT Biofarma (Persero)",
  "PT Kimia Farma Tbk",
  "PT Indofarma Tbk",
  "PT Perkebunan Nusantara III (Persero)",
  "PT Perkebunan Nusantara I",
  "PT Perkebunan Nusantara IV",
  "PT Pertamina (Persero)",
  "PT Pertamina Hulu Energi",
  "PT Kilang Pertamina Internasional",
  "PT Pertamina Patra Niaga",
  "PT Perusahaan Gas Negara Tbk",
  "PT Pertamina Power Indonesia",
  "PT Perusahaan Listrik Negara (Persero)",
  "PT PLN Indonesia Power",
  "PT Telkom (Persero), Tbk",
  "PT Telekomunikasi Selular",
  "PT Dayamitra Telekomunikasi Tbk",
  "PT Danareksa (Persero)",
];


