// List of 78 Indonesian State-Owned Enterprises (BUMNs)
export const COMPANIES = [
  "PT Adhi Karya (Persero) Tbk",
  "PT Angkasa Pura Indonesia",
  "PT Aneka Tambang Indonesia Tbk",
  "PT ASDP Indonesia Ferry (Persero)",
  "PT Aviasi Pariwisata Indonesia (Persero)",
  "PT Berdikari",
  "PT Biofarma (Persero)",
  "PT Biro Klasifikasi Indonesia (Persero)",
  "PT Brantas Abipraya (Persero)",
  "PT Bukit Asam Tbk",
  "PT Citilink Indonesia",
  "PT Dahana",
  "PT Danareksa (Persero)",
  "PT Dayamitra Telekomunikasi Tbk",
  "PT Dirgantara Indonesia",
  "PT Garam",
  "PT Garuda Indonesia (Persero) Tbk",
  "PT Garuda Maintenance Facility Aero Asia Tbk",
  "PT Hotel Indonesia Natour",
  "PT Hutama Karya (Persero)",
  "PT Indofarma Tbk",
  "PT Indonesia Asahan Alumunium",
  "PT Industri Kereta Api (Persero)",
  "PT Jasa Marga (Persero) Tbk",
  "PT Kereta Api Indonesia (Persero)",
  "PT Kilang Pertamina Internasional",
  "PT Kimia Farma Tbk",
  "PT Krakatau Steel (Persero) Tbk",
  "PT LEN Industri (Persero)",
  "PT Mineral Industri Indonesia (Persero)",
  "PT PAL Indonesia",
  "PT Pelabuhan Indonesia (Persero)",
  "PT Pelayaran Nasional Indonesia (Persero)",
  "PT Pelindo Jasa Maritim",
  "PT Pelindo Multi Terminal",
  "PT Pelindo Solusi Logistik",
  "PT Pelindo Terminal Petikemas",
  "PT Pembangunan Perumahan (Persero) Tbk",
  "PT Pengembangan Pariwisata Indonesia",
  "PT Perikanan Indonesia",
  "PT Perkebunan Nusantara I",
  "PT Perkebunan Nusantara III (Persero)",
  "PT Perkebunan Nusantara IV",
  "PT Pertamina (Persero)",
  "PT Pertamina Hulu Energi",
  "PT Pertamina Patra Niaga",
  "PT Pertamina Power Indonesia",
  "PT Perusahaan Gas Negara Tbk",
  "PT Perusahaan Listrik Negara (Persero)",
  "PT Perusahaan Perdagangan Indonesia",
  "PT Petrokimia Gresik",
  "PT Pindad",
  "PT PLN Indonesia Power",
  "PT Pos Indonesia (Persero)",
  "PT Pupuk Indonesia (Persero)",
  "PT Pupuk Indonesia Niaga",
  "PT Pupuk Indonesia Pangan",
  "PT Pupuk Iskandar Muda",
  "PT Pupuk Kaltim",
  "PT Pupuk Kujang",
  "PT Pupuk Sriwijaya Palembang",
  "PT Rajawali Nusantara Indonesia (Persero)",
  "PT Rekayasa Industri",
  "PT Sang Hyang Seri",
  "PT Semen Baturaja Tbk",
  "PT Semen Gresik",
  "PT Semen Indonesia (Persero) Tbk",
  "PT Semen Padang",
  "PT Semen Tonasa",
  "PT Sucofindo",
  "PT Surveyor Indonesia",
  "PT Taman Wisata Candi Borobudur, Prambanan dan Ratu Boko",
  "PT Telkom (Persero), Tbk",
  "PT Telekomunikasi Selular",
  "PT Timah Tbk",
  "PT Waskita Karya (Persero) Tbk",
  "PT Wijaya Karya (Persero) Tbk",
];


